### ISSUE TITLE
Clean up old and unused code

### ISSUE THREAD

**Issue by symroe** [DemocracyClub/electionleaflets#266]
This is an issue that's being worked on, but I'm using this as a general task list that is likely to span a number of PRs. 

It's initially a place to capture comments from #257.

```[tasklist]
### Tasks
- [ ] Remove JSON fixtures as per https://github.com/DemocracyClub/electionleaflets/pull/257#issuecomment-2503683477
- [ ] Remove `Constituency` model and related code
- [ ] Remove empty / pointless files, e.g `elections/tests.py` and `elections/views.py`
- [ ] Deal with "legacy" app
- [ ] Remove dead management commands
- [ ] Remove `Country` model and related code, replace with NUTS1 codes
- [ ] Remove `aloe` and replace anything needed with `Playwright`
- [ ] Remove all MaPit and geocoding features 
- [ ] Remove `Party` model and related `uk_political_parties` project, migrate data to on-leaflet fields.
- [ ] Switch to using UV and sort out project requirements
```
